
INSERT INTO ROOT.TB_EXERCICIO (TXT_NOME_EXERCICIO, TXT_TIPO_EXERCICIO) 	VALUES ('BICEPS_BARRA_ROSCA_PRON_POLIA', 'BICEPS')
INSERT INTO ROOT.TB_EXERCICIO (TXT_NOME_EXERCICIO, TXT_TIPO_EXERCICIO) 	VALUES ('PEIT_GRAVITON', 'PEITORAL')
INSERT INTO ROOT.TB_EXERCICIO (TXT_NOME_EXERCICIO, TXT_TIPO_EXERCICIO) 	VALUES ('TRICEPS_FRANCES_UNI_HALT_TRICEPS', 'TRICEPS')
INSERT INTO ROOT.TB_EXERCICIO (TXT_NOME_EXERCICIO, TXT_TIPO_EXERCICIO) 	VALUES ('OMBRO_ELEV_FRON_PRON_P_D_ELEV_FRON_SUP', 'OMBRO')
INSERT INTO ROOT.TB_EXERCICIO (TXT_NOME_EXERCICIO, TXT_TIPO_EXERCICIO) 	VALUES ('COXAS_AVANCO_BARRA_AVANCO', 'PERNAS')
INSERT INTO ROOT.TB_EXERCICIO (TXT_NOME_EXERCICIO, TXT_TIPO_EXERCICIO) 	VALUES ('DORS_BARRA_SUPINADA', 'DORSAIS')
